In [1]:
import pandas as pd   
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'  #解决多线程问题
import torch
data_file=pd.read_csv('../how_use_torch/data.csv')
print(data_file.head())

   1  2  3
0  4  5  6


In [2]:
#使用torch进行线性代数运算
a=torch.tensor([[1,2,3],[4,5,6]])
print(id(a))
print("a的形状:", a.shape)
b=torch.tensor([[7,8],[9,10],[11,12]])
print("b的形状:", b.shape)
print(id(b))
c=torch.mm(a,b)
print("a和b的矩阵乘法结果c:")
print(c)
print("c的形状:", c.shape)
print(id(c))

3221993118912
a的形状: torch.Size([2, 3])
b的形状: torch.Size([3, 2])
3221377861984
a和b的矩阵乘法结果c:
tensor([[ 58,  64],
        [139, 154]])
c的形状: torch.Size([2, 2])
3221993118752


In [3]:
#给出对称矩阵与非对称矩阵
system_matrix=torch.tensor([[1,2,3],[2,5,6],[3,6,9]])
non_system_matrix=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
#检测设备
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("当前设备:", device)

当前设备: cuda


In [9]:
#使用矩阵的转置
b=torch.arange(1, 13).reshape(3, 4)
print("b的形状:", b.shape)
print("b的内容:")
print(b)
print("b的转置:")
print(b.t())
print("b和b转置的矩阵乘法结果:")
print(torch.mm(b,b.T))
print(torch.mm(b,b.t()))
print(b@b.T)

b的形状: torch.Size([3, 4])
b的内容:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
b的转置:
tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])
b和b转置的矩阵乘法结果:
tensor([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]])
tensor([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]])
tensor([[ 30,  70, 110],
        [ 70, 174, 278],
        [110, 278, 446]])


# 本Jupyter Notebook已导入pandas和torch，并设置了多线程环境变量。
# 已加载数据文件到data_file（DataFrame），并展示了其内容。
# 已定义多个torch张量变量：a、b、c、system_matrix、non_system_matrix。
# a和b用于线性代数运算，c为a和b的矩阵乘法结果。
# system_matrix为对称矩阵，non_system_matrix为非对称矩阵。
# 已检测设备并赋值给device（当前为cuda）。
# 展示了矩阵b的转置及其与自身转置的乘法结果。