In [1]:
import os
os.environ['KMP_DUPLICATE_LIB_OK']='TRUE'


In [2]:
import torch
torch.tensor([1,2,3])
print(torch.tensor([1,2,3]))

tensor([1, 2, 3])


In [4]:
#简单介绍广播机制
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
print(a,"对应的形状为：", a.shape,"\n", b,"对应的形状为：", b.shape)
print("a+b的结果为：")
print(a+b)
print("a+b的结果对应的形状为：", (a+b).shape)

tensor([[0],
        [1],
        [2]]) 对应的形状为： torch.Size([3, 1]) 
 tensor([[0, 1]]) 对应的形状为： torch.Size([1, 2])
a+b的结果为：
tensor([[0, 1],
        [1, 2],
        [2, 3]])
a+b的结果对应的形状为： torch.Size([3, 2])


In [6]:
#使用torch进行简单的运算赋值
a[:,0]=100
print("修改a的第一列为100后，a的结果为：")
print(a)

修改a的第一列为100后，a的结果为：
tensor([[100],
        [100],
        [100]])


In [8]:
#给出内存相关的例子
before=id(a)
print("修改前a的id为：", before)
a=a+b
id(a)==before
print("修改后a的id为：", id(a))

修改前a的id为： 2751724006816
修改后a的id为： 2751724004976


In [10]:
#给出内存相关的例子
before=id(a)
print("修改前a的id为：", before)
a+=b
if(id(a)==before):
    print("a和b的id相同")
else:
    print("a和b的id不同")
print("修改后a的id为：", id(a))

修改前a的id为： 2751724004976
a和b的id相同
修改后a的id为： 2751724004976


In [11]:
#torch and numpy
import numpy as np
a_num=a.numpy()
b_tor=torch.tensor(a_num)
print("a_num的类型为：", type(a_num))
print("b_tor的类型为：", type(b_tor))

a_num的类型为： <class 'numpy.ndarray'>
b_tor的类型为： <class 'torch.Tensor'>
