In [4]:
import os 
os.environ['KMP_DUPLICATE_LIB_OK']='TRUE'   
import torch


In [5]:
#利用torch进行多维张量的求和操作
#torch.sum(input, dim, keepdim=False, dtype=None) -> Tensor
a=torch.arange(12).reshape(3,4)
print(a)
a_sum_0=a.sum(dim=0)
a_sum_1=a.sum(dim=1)
print(a_sum_0)
print(a_sum_1)
try:
    a_sum_2=a.sum(dim=2)
except Exception as e:
    print(e)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([12, 15, 18, 21])
tensor([ 6, 22, 38])
Dimension out of range (expected to be in range of [-2, 1], but got 2)


In [6]:
#利用torch进行矩阵的向量机乘
b=torch.ones(3,4,dtype=torch.float32)
print(b)  

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [7]:
#计算范式
c_0=torch.norm(b,dim=0)
print(c_0)
c_1=torch.norm(b,dim=1)
print(c_1)
#整体上计算遵循的是列向量为0，行向量为1的原则

tensor([1.7321, 1.7321, 1.7321, 1.7321])
tensor([2., 2., 2.])


In [8]:
#什么是范数呢
#范数是一个标量，用于表示向量或矩阵的大小或长度。
#在torch中，范数的计算可以使用torch.norm()函数实现。
#torch.norm(input, p='fro', dim=None, keepdim=False, dtype=None) -> Tensor
#其中，p参数指定范数的类型，dim参数指定计算范数的维
#度，keepdim参数指定是否保持维度不变，dtype参数指定输出的类型。
#矩阵的弗罗贝乌斯范数（Frobenius norm）是矩阵元素的平方和的平方根。
#它是矩阵的一个重要性质，常用于衡量矩阵的大小或复杂度。
#弗罗贝乌斯范数可以通过torch.norm()函数计算，默认情况下p='fro'。
print(torch.ones(6,6))
print(torch.norm(torch.ones(6,6)))
print(torch.norm(torch.ones(6,6),dim=0))
print(torch.norm(torch.ones(6,6),dim=1))
#torch.norm(torch.ones(6,6),p=1)
#torch.norm(torch.ones(6,6),p=2)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor(6.)
tensor([2.4495, 2.4495, 2.4495, 2.4495, 2.4495, 2.4495])
tensor([2.4495, 2.4495, 2.4495, 2.4495, 2.4495, 2.4495])


#对于多个矩阵维度的sum的理解
#torch.sum(input, dim, keepdim=False, dtype=None) -> Tensor
对于一个维度为[5,4]的矩阵
当dim=0时，我是在遍历所有的矩阵行，留下的是一个矩阵的列，即[4]
当dim=1时，我正在遍历所有的矩阵列，留下一个矩阵的行，即[5]
按照某一个维度进行矩阵运算求和，便留下了一个新的矩阵

In [9]:
a=torch.ones((2,5,4))
print(a)
print(a.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([2, 5, 4])


In [10]:
b=a.sum(dim=0)
print(b.shape)
c=a.sum(dim=1)
print(c)
print(c.shape)
d=a.sum(dim=2,keepdim=True)
print(d)
print(d.shape)

torch.Size([5, 4])
tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.]])
torch.Size([2, 4])
tensor([[[4.],
         [4.],
         [4.],
         [4.],
         [4.]],

        [[4.],
         [4.],
         [4.],
         [4.],
         [4.]]])
torch.Size([2, 5, 1])


In [13]:
#利用torch完成导数的求解
x=torch.tensor(2.0,requires_grad=True)
y=x**2+2*x+1
print(f"x={x}")
print(f"y=x**2+2*x+1={y}")

#计算梯度
y.backward()
print(f"dy/dx={x.grad}")
print(f"导数的理论值大小为:6.0")

x=2.0
y=x**2+2*x+1=9.0
dy/dx=6.0
导数的理论值大小为:6.0


In [17]:
#多变量的函数求导
x=torch.tensor(3.0,requires_grad=True)
y=torch.tensor(4.0,requires_grad=True)

f=x**2+y**2+2*x*y
print(f"f={f}")

#梯度计算 完成反向传播
f.backward()
print(f"df/dx={x.grad}")
print(f"df/dy={y.grad}")

#完成比对理论值与实际值
flag1=(x.grad==2*x+2*y)
flag2=(y.grad==2*y+2*x)
print(flag1)
print(flag2)


f=49.0
df/dx=14.0
df/dy=14.0
tensor(True)
tensor(True)


In [21]:
#完成高级自动求导
x=torch.randn(3,requires_grad=True)
y=x*2
while y.data.norm()<1000:
    y=y*2
print(f"y={y}")
print(f"y的范数为:{y.data.norm()}")

v=torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(v)
print(f"x的梯度: {x.grad}")
print("这里计算的是Jacobian矩阵与向量v的乘积\n")

# 零梯度和梯度累积
print("=== 梯度累积与清零 ===")
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2

# 第一次反向传播
y.backward()
print(f"第一次反向传播后x.grad = {x.grad}")

# 再次计算并反向传播（梯度会累积）
y = x ** 2
y.backward()
print(f"第二次反向传播后x.grad = {x.grad} (注意梯度累积了)")

# 清零梯度
x.grad.zero_()
y = x ** 2
y.backward()
print(f"清零梯度后再次反向传播x.grad = {x.grad}\n")

y=tensor([-1275.2042,   -43.2743,   442.2977], grad_fn=<MulBackward0>)
y的范数为:1350.4241943359375
x的梯度: tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])
这里计算的是Jacobian矩阵与向量v的乘积

=== 梯度累积与清零 ===
第一次反向传播后x.grad = 4.0
第二次反向传播后x.grad = 8.0 (注意梯度累积了)
清零梯度后再次反向传播x.grad = 4.0



In [25]:
print("=== 实际应用：简单线性回归 ===")
# 生成示例数据
torch.manual_seed(42)
X = torch.randn(100, 1)
y_true = 3 * X + 2 + 0.1 * torch.randn(100, 1)  # y = 3x + 2 + noise

# 初始化参数
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

# 训练过程
learning_rate = 0.01
for epoch in range(1000):
    # 前向传播
    y_pred = w * X + b
    
    # 计算损失 (均方误差)
    loss = torch.mean((y_pred - y_true) ** 2)
    
    # 反向传播
    loss.backward()
    
    # 更新参数
    with torch.no_grad():  # 不跟踪梯度的更新操作
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        
        # 清零梯度
        w.grad.zero_()
        b.grad.zero_()
    if epoch %100 ==0:
        print(f"epoch={epoch}")
        print(f"真实权重: 3, 学习到的权重: {w.item():.3f}")
        print(f"真实偏置: 2, 学习到的偏置: {b.item():.3f}")

print(f"训练完成:")
print(f"真实权重: 3, 学习到的权重: {w.item():.3f}")
print(f"真实偏置: 2, 学习到的偏置: {b.item():.3f}")

=== 实际应用：简单线性回归 ===
epoch=0
真实权重: 3, 学习到的权重: 1.041
真实偏置: 2, 学习到的偏置: 0.042
epoch=100
真实权重: 3, 学习到的权重: 2.754
真实偏置: 2, 学习到的偏置: 1.774
epoch=200
真实权重: 3, 学习到的权重: 2.970
真实偏置: 2, 学习到的偏置: 1.977
epoch=300
真实权重: 3, 学习到的权重: 2.997
真实偏置: 2, 学习到的偏置: 2.001
epoch=400
真实权重: 3, 学习到的权重: 3.001
真实偏置: 2, 学习到的偏置: 2.003
epoch=500
真实权重: 3, 学习到的权重: 3.001
真实偏置: 2, 学习到的偏置: 2.004
epoch=600
真实权重: 3, 学习到的权重: 3.001
真实偏置: 2, 学习到的偏置: 2.004
epoch=700
真实权重: 3, 学习到的权重: 3.001
真实偏置: 2, 学习到的偏置: 2.004
epoch=800
真实权重: 3, 学习到的权重: 3.001
真实偏置: 2, 学习到的偏置: 2.004
epoch=900
真实权重: 3, 学习到的权重: 3.001
真实偏置: 2, 学习到的偏置: 2.004
训练完成:
真实权重: 3, 学习到的权重: 3.001
真实偏置: 2, 学习到的偏置: 2.004
