In [1]:
import os 
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt 
import numpy as np
import time

In [5]:
#定义二维互相关运算
def corr2d(X,K):
    h,w=K.shape  
    Y=torch.zeros((X.shape[0]-h+1,X.shape[1]-w+1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i,j]=torch.sum(X[i:i+h,j:j+w]*K)
    return Y

#给出多通道的输入和输出的例子
def corr2d_multi_in(X,K):
    return sum(corr2d(x,k) for x,k in zip(X,K))

def corr2d_multi_in_out(X,K):
    return torch.stack([corr2d_multi_in(X,k) for k in K],dim=0)

#给出对应的数据
X=torch.tensor([[[0.0,1.0,2.0],[3.0,4.0,5.0],[6.0,7.0,8.0]],[[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]]],dtype=torch.float32)
K=torch.tensor([[[0.0,1.0],[2.0,3.0]],[[1.0,2.0],[3.0,4.0]]],dtype=torch.float32)
K=torch.stack((K,K+1,K+2),dim=0)  #增加一个通道
print(corr2d_multi_in_out(X,K))  #输出结果为tensor

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])


torch.stack 函数用法
torch.stack 是 PyTorch 中一个非常有用的函数，用于沿着一个新的维度对输入的张量进行堆叠（stacking）。这在处理多通道数据（如图像的 RGB 通道）或需要批量操作时特别有用。

1. 基本语法
python
torch.stack(tensors, dim=0, *, out=None)
tensors (Sequence of Tensors): 需要堆叠的张量序列。这些张量必须具有相同的形状。
dim (int, optional): 新维度的位置。默认值为 0。
out (Tensor, optional): 结果张量的输出位置。如果提供，结果将被写入该张量中。
2. 功能说明
torch.stack 的主要功能是：

增加维度：在指定的维度上增加一个新的维度，并将输入的张量沿着这个新维度进行堆叠。
保持形状一致：所有输入张量的形状必须相同。
3. 示例用法
3.1 基本用法
假设我们有两个形状相同的张量 x 和 y：

python
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
我们可以使用 torch.stack 将它们沿着新的维度进行堆叠：

python
z = torch.stack((x, y))
print(z)
输出将是：

python
tensor([[1, 2, 3],
        [4, 5, 6]])
这里，z 的形状为 (2, 3)，其中第一个维度（大小为 2）是新添加的维度。

3.2 指定堆叠维度
我们也可以指定堆叠的维度。例如，沿着第二个维度（dim=1）进行堆叠：

python
z = torch.stack((x, y), dim=1)
print(z)
输出将是：

python
tensor([[1, 4],
        [2, 5],
        [3, 6]])
这里，z 的形状为 (3, 2)，第二个维度（大小为 2）是新添加的维度。

3.3 堆叠多个张量
torch.stack 也可以用于堆叠多个张量。例如，我们有三个张量 x, y 和 z：

python
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
z = torch.tensor([7, 8, 9])

result = torch.stack((x, y, z))
print(result)
输出将是：

python
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
4. 应用场景
批量数据处理：在深度学习中，经常需要将多个样本堆叠成一个批次（batch）来进行训练。
多通道数据处理：如处理 RGB 图像时，可以将三个通道的张量堆叠在一起。
时间序列数据：在处理时间序列数据时，可以将不同时间点的数据堆叠在一起。
5. 与 torch.cat 的区别
torch.stack：在新维度上进行堆叠，会增加一个新的维度。
torch.cat：在现有维度上进行拼接，不会增加新的维度。
6. 总结
torch.stack 是一个非常实用的函数，用于在指定维度上对多个张量进行堆叠。它在处理批量数据、多通道数据和时间序列数据等场景中有着广泛的应用。理解其用法和应用场景，可以帮助你更高效地进行张量操作。

希望以上解释对你理解 torch.stack 的用法有所帮助！如果有任何问题或需要进一步的解释，请随时提问